TARGET     = obj2bim
MODE       = exe
OBJS       = $(TARGET).obj autodec.obj
STACKSIZE  = 0x1c00000 # 28MB (default + 12MB)

INCPATH    = ../z_tools/win32/
CC1OPT     = -Dmain=main0
include ../z_tools/com_mak.txt
