TARGET     = tstdstk1
MODE       = exe
OBJS       = $(TARGET).obj dtk1s.obj
STACKSIZE  = 0x1000000 # 16MB (default)

INCPATH    = ../z_tools/win32/
CC1OPT     = -Dmain=main0
include ../z_tools/com_mak.txt
