include ../include/rules.mak

OBJS = call.o decl.o expr.o pt.o typeck2.o class.o decl2.o error.o lex.o \
	parse.o ptree.o rtti.o spew.o typeck.o cvt.o except.o friend.o init.o \
	method.o search.o semantics.o tree.o repo.o dump.o optimize.o mangle.o \
	cp-lang.o

###

all :
	$(MAKER) $(OBJS)

clean :
	-$(DEL) *.o
