TARGET     = bim2bin
MODE       = exe
OBJS       = $(TARGET).obj
STACKSIZE  = 0x1000000 # 32MB (default)

INCPATH    = ../z_tools/win32/
CC1OPT     = -Dmain=main0
include ../z_tools/com_mak.txt
