include include/rules.mak

clean :
	$(MAKEC) toolstdc  clean
	$(MAKEC) toolw32   clean
	$(MAKEC) nasklib   clean
	$(MAKEC) go_lib    clean
	$(MAKEC) libiberty clean
	$(MAKEC) intl      clean
	$(MAKEC) cp        clean
	$(MAKEC) gcc       clean
	$(MAKEC) drv_w32   clean
	$(MAKEC) drv_stdc  clean
	$(MAKEC) drv_osa   clean
	$(MAKEC) golibc    clean
	$(MAKEC) w32clibc  clean
